
FROM modelscope-registry.cn-beijing.cr.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-py311-torch2.3.1-1.26.0 as ms
RUN modelscope download --cache_dir /root/.cache/modelscope/hub/models/ --model Qwen/Qwen2.5-VL-3B-Instruct

FROM vllm-cpu-env:v0.0.2
COPY --from=ms /root/.cache/modelscope /root/.cache/modelscope
