
name: Push Image Arm64

on: push

permissions:
  contents: read

jobs:
  lint-and-deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

       #Python is required because ct lint runs Yamale and yamllint which require Python.
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.13'

      - name: Build the Docker image vllm cpu
        run: |
          echo "login aliyun registry"
          docker login --username=huiwq1990@163.com -p Cr@123456 registry.cn-beijing.aliyuncs.com/huiwq1990/public
          echo "build image"
          tag=vllm-cpu-env-v0.9.0.1-02
          docker buildx build --platform=linux/arm64 --build-arg VLLM_CPU_DISABLE_AVX512="true" --push -f docker/Dockerfile.arm -t registry.cn-beijing.aliyuncs.com/huiwq1990/public:${tag}-arm64 .
